version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_TDEX_CONNECT_IP
      APP_PORT: $APP_TDEX_CONNECT_PORT
  
  tdexd:
    image: ghcr.io/tdex-network/tdexd:v0.8.16@sha256:5e8122f25a7ab924a177cefab9609a28a7842ec9e6bd5511ad77c3aa61ffa21b
    tty: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9090:9090
    volumes:
      - ${APP_DATA_DIR}/tdex-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_LOG_LEVEL: 5
      TDEX_EXPLORER_ENDPOINT: https://liquid.network/liquid/api
      TDEX_OPERATOR_LISTENING_PORT: 9090
      TDEX_TRADE_LISTENING_PORT:  9090
      TDEX_NO_OPERATOR_TLS: "true"
      TDEX_CONNECT_ADDR: "$DEVICE_HOSTNAME:9090"
      TDEX_CONNECT_PROTO: http

  dashboard:
    image: ghcr.io/tdex-network/dashboard:v0.1.35@sha256:9f388375966e7ac6ad1909b0acb2922a7650ab0f7305862935140a5a155dca83
    restart: on-failure
    environment:
      USE_PROXY: "false"
    ports:
      - 8080:8080
