version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: tdex_dashboard_1
      APP_PORT: 8080
  
  tdexd:
    image: ghcr.io/tdex-network/tdexd:v0.8.17@sha256:10c648982648c71c7c31456c1fc64a3f5c03763a1879cc926e321cd6081c2415
    tty: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9095:9090
    volumes:
      - ${APP_DATA_DIR}/tdex-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_LOG_LEVEL: 5
      TDEX_EXPLORER_ENDPOINT: https://liquid.network/liquid/api
      TDEX_OPERATOR_LISTENING_PORT: 9090
      TDEX_TRADE_LISTENING_PORT:  9090
      TDEX_NO_OPERATOR_TLS: "true"
      TDEX_CONNECT_ADDR: "tdexd:9090"
      TDEX_CONNECT_PROTO: http

  dashboard:
    image: ghcr.io/tdex-network/dashboard:v0.1.36@sha256:57bc9a2d1a4db7dfe4208de6bbec9edbfaad69133ef80c788a984466b9ebbc90
    restart: on-failure
    environment:
      USE_PROXY: "false"
      IS_PACKAGED: "true"
      TDEX_DAEMON_URL: "tdexd:9090"