version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: tdex_caddy_1
      APP_PORT: 8080
  
  tdexd:
    image: ghcr.io/tdex-network/tdexd:v0.8.19@sha256:5a2c0db9f74812e67aa98f50f396e81edd23ef49cb6797b084027ba6124db707
    tty: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/tdex-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_LOG_LEVEL: 5
      TDEX_OPERATOR_LISTENING_PORT: 9090
      TDEX_TRADE_LISTENING_PORT:  9090
      TDEX_NO_OPERATOR_TLS: "true"
      # these vars are used to generate the connect URL
      # we assume to always show the external endpoint
      # reachable remotely by other dashboards via Tor
      TDEX_CONNECT_ADDR: "$APP_TDEX_DAEMON_HIDDEN_SERVICE:9000"
      TDEX_CONNECT_PROTO: http
    
  dashboard:
    image: ghcr.io/tdex-network/dashboard:v0.1.42@sha256:bda1bd0ac14f8d1466e83ba5c8148cede77f16e7606f50aefa22c7fd3d9fd7a9
    restart: on-failure
    environment:
      USE_PROXY: "false"
      IS_PACKAGED: "true"
      TRADER_HIDDEN_SERVICE:  "$APP_TDEX_DAEMON_HIDDEN_SERVICE:9000"
  
  caddy:
    image: caddy:2.6.1-alpine@sha256:21dbf9101c1eae0e2228f386eefab509d462710c2da97ba45d61c083f3e74fc1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/caddy-data/Caddyfile:/etc/caddy/Caddyfile