version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: tdex_dashboard_1
      APP_PORT: 3030
  
  tdexd:
    image: ghcr.io/tdex-network/tdexd:v0.8.19@sha256:5a2c0db9f74812e67aa98f50f396e81edd23ef49cb6797b084027ba6124db707
    tty: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9095:9090
    volumes:
      - ${APP_DATA_DIR}/tdex-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_LOG_LEVEL: 5
      TDEX_EXPLORER_ENDPOINT: https://liquid.network/liquid/api
      TDEX_OPERATOR_LISTENING_PORT: 9090
      TDEX_TRADE_LISTENING_PORT:  9090
      TDEX_NO_OPERATOR_TLS: "true"

  dashboard:
    image: ghcr.io/tdex-network/dashboard:v0.1.39@sha256:4888ec6f1baa2244d068edbb0b0d532f67399cfef838ab3fe536b8c4280cd036
    restart: on-failure
    environment:
      USE_PROXY: "false"
      IS_PACKAGED: "true"
  
  caddy:
    image: caddy:alpine
    restart: on-failure
    ports:
      - "3030:3030"
    volumes:
      - ${APP_DATA_DIR}/caddy-data/Caddyfile:/etc/caddy/Caddyfile