version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: tdex_caddy_1
      APP_PORT: 8080
  
  tdexd:
    image: ghcr.io/tdex-network/tdexd:v0.0.9@sha256:77729e6c0019752059cc5bf624675e261abd8b856e0a7e8f59889b7ec0a35eb3
    tty: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/tdex-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_LOG_LEVEL: 5
      TDEX_OPERATOR_LISTENING_PORT: 9090
      TDEX_TRADE_LISTENING_PORT:  9090
      TDEX_NO_OPERATOR_TLS: "true"
      # these vars are used to generate the connect URL
      # we assume to always show the external endpoint
      # reachable remotely by other dashboards via Tor
      TDEX_CONNECT_ADDR: "$APP_TDEX_DAEMON_HIDDEN_SERVICE"
      TDEX_CONNECT_PROTO: http
    
  dashboard:
    image: ghcr.io/tdex-network/dashboard:v0.1.47@sha256:31d7636e3d9d6924d46b6e8aed5fef80f44df5ea936d936043141fc10f823652
    restart: on-failure
    environment:
      USE_PROXY: "false"
      IS_PACKAGED: "true"
      TRADER_HIDDEN_SERVICE:  "$APP_TDEX_DAEMON_HIDDEN_SERVICE"
  
  caddy:
    image: caddy:2.6.1-alpine@sha256:21dbf9101c1eae0e2228f386eefab509d462710c2da97ba45d61c083f3e74fc1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/caddy-data/Caddyfile:/etc/caddy/Caddyfile